[tools]
bun = "latest"

[env]
BETTER_AUTH_URL = "http://localhost:3000"
BETTER_AUTH_SESSION_EXPIRES_IN = 28800
BETTER_AUTH_SESSION_UPDATE_AGE = 3600
KEYCLOAK_LOGOUT_ENABLED = "true"

# Move to secret management solution in production
KEYCLOAK_CLIENT_ID = "sveltekit-app-better-dev2"
KEYCLOAK_CLIENT_SECRET = ""
KEYCLOAK_ISSUER = ""
REDIS_URL = ''
BETTER_AUTH_SECRET = ""
# Database (mix of plain and encrypted)
DB_USER = "postgres"
DB_PASSWORD = ""
DB_HOST = "localhost"
DB_NAME = "starter"
DATABASE_URL = "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}"

[tasks]
# Common Bun tasks
dev = "bun --bun run dev"
preview = "bun --bun run preview ./build"
test = "bun --bun run test"
build = "bun --bun run build"
install = "bun install"
up = "docker compose --env-file .env.docker up --build"


[settings]
task_output = "quiet"
